#!/usr/bin/env node
/**
 * Build script to embed source data as TypeScript modules.
 * Generates:
 * - src/data/trainData.generated.ts (CSV_DATA)
 * - src/data/routeData.generated.ts (OLD_ROUTE_MAP)
 */

const fs = require("fs");
const path = require("path");

// Get the project root directory (parent of scripts folder)
const projectRoot = path.dirname(__dirname);
const csvPath = path.join(projectRoot, "src/data/Train_details_22122017.csv");
const schedulesPath = path.join(projectRoot, "src/data/schedules.json");
const csvOutputPath = path.join(projectRoot, "src/data/trainData.generated.ts");
const routeOutputPath = path.join(projectRoot, "src/data/routeData.generated.ts");

function normalizeTrainNumber(value) {
  const text = String(value || "").trim().toUpperCase();
  if (!text) return "";

  const match = text.match(/^(\d+)(.*)$/);
  if (!match) return text;

  const numeric = String(Number(match[1]));
  const suffix = (match[2] || "").trim();
  return `${numeric}${suffix}`;
}

function toDayNumber(value) {
  if (typeof value === "number" && Number.isFinite(value)) {
    return value;
  }

  if (typeof value === "string" && value.trim() !== "") {
    const parsed = Number(value);
    return Number.isFinite(parsed) ? parsed : Number.MAX_SAFE_INTEGER;
  }

  return Number.MAX_SAFE_INTEGER;
}

try {
  const csvContent = fs.readFileSync(csvPath, "utf-8");

  // Build train number whitelist from CSV to keep route output lightweight.
  const csvLines = csvContent.split(/\r?\n/).slice(1).filter(Boolean);
  const csvTrainNumbers = new Set();
  for (const line of csvLines) {
    const firstComma = line.indexOf(",");
    const rawNumber = firstComma === -1 ? line : line.slice(0, firstComma);
    const normalized = normalizeTrainNumber(rawNumber);
    if (normalized) {
      csvTrainNumbers.add(normalized);
    }
  }

  const schedulesRaw = fs.readFileSync(schedulesPath, "utf-8");
  const schedules = JSON.parse(schedulesRaw);
  const grouped = new Map();

  for (let index = 0; index < schedules.length; index += 1) {
    const row = schedules[index] || {};
    const normalizedTrain = normalizeTrainNumber(row.train_number);
    if (!normalizedTrain || !csvTrainNumbers.has(normalizedTrain)) {
      continue;
    }

    const stationCode = String(row.station_code || "").trim().toUpperCase();
    if (!stationCode) {
      continue;
    }

    const stationName = String(row.station_name || "").trim() || stationCode;
    const day = toDayNumber(row.day);
    const existing = grouped.get(normalizedTrain) || [];
    existing.push({ stationCode, stationName, day, order: index });
    grouped.set(normalizedTrain, existing);
  }

  const routeMap = {};
  for (const [trainNumber, points] of grouped.entries()) {
    points.sort((left, right) => {
      if (left.day !== right.day) {
        return left.day - right.day;
      }
      return left.order - right.order;
    });

    const route = [];
    for (const point of points) {
      const previous = route[route.length - 1];
      if (previous && previous.stationCode === point.stationCode) {
        continue;
      }
      route.push({
        stationCode: point.stationCode,
        stationName: point.stationName,
        seq: route.length + 1,
      });
    }

    if (route.length > 0) {
      routeMap[trainNumber] = route;
    }
  }

  // Escape the CSV content for use in a JavaScript string
  const escaped = csvContent
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r");

  const csvTsContent = `// Auto-generated file - do not edit manually
// Generated by scripts/embedCSV.js during build

/**
 * CSV data embedded as string at build time
 * Contains train schedule information from Train_details_22122017.csv
 */
export const CSV_DATA = "${escaped}";
`;

  const routeTsContent = `// Auto-generated file - do not edit manually
// Generated by scripts/embedCSV.js during build

export type OldRoutePoint = {
  stationCode: string;
  stationName: string;
  seq: number;
};

/**
 * Legacy full-route points derived from schedules.json for trains present in CSV.
 * Keyed by normalized train number.
 */
export const OLD_ROUTE_MAP: Record<string, OldRoutePoint[]> = ${JSON.stringify(routeMap)};
`;

  fs.writeFileSync(csvOutputPath, csvTsContent, "utf-8");
  fs.writeFileSync(routeOutputPath, routeTsContent, "utf-8");
  console.log("✓ CSV data embedded into src/data/trainData.generated.ts");
  console.log("✓ Old route map embedded into src/data/routeData.generated.ts");
} catch (error) {
  console.error("✗ Failed to embed CSV data:", error.message);
  process.exit(1);
}
